### ISSUE TITLE
Version 1.15.2

### ISSUE THREAD

**Issue by kuba150** [kangarko/ChatControl-Free#382] opened 2020-02-04 23:31 UTC
When you plan to upgrade free version od your plugin to Minecraft version 1.15.2

**Comment by kangarko** [comment] 2020-02-05 08:55
It does not work?

**Comment by kuba150** [comment] 2020-02-05 14:16
Unfortunately yes, please do something with this because I need this
awesome plugin to my server work properly

śr., 5.02.2020, 09:55 użytkownik Matej Pacan <notifications@github.com>
napisał:

**Comment by diannetea** [comment] 2020-02-06 15:13
I can't get it to work either, using venturechat for formatting

**Comment by kuba150** [comment] 2020-02-06 15:20
Please try to do something

czw., 6.02.2020, 16:13 użytkownik diannetea <notifications@github.com>
napisał:

**Comment by kangarko** [comment] 2020-02-06 16:39
How exactly it does not work?

**Comment by diannetea** [comment] 2020-02-06 20:50
I've done some more testing and it looks like it actually does work for everything except formatting chat.  It blocks commands correctly, but it does not rewrite or replace anything said.

**Comment by diannetea** [comment] 2020-02-07 01:23
NEVERMIND IM STUPID AND HAD A BYPASS ON MYSELF

**Comment by kuba150** [comment] 2020-02-07 22:17
What xD

pt., 7.02.2020, 02:23 użytkownik diannetea <notifications@github.com>
napisał:

**Comment by kuba150** [comment] 2020-02-07 22:24
This is my wrong that ChatControl not working on my server or yours?

pt., 7.02.2020, 23:17 użytkownik Jakub M <kuba.29000@gmail.com> napisał:

**Comment by kangarko** [comment] 2020-02-09 09:07
Closing, if there is a **specific** problem preventing ChatControl to work, open a new tickets with **exact** steps to reproduce the problem and if you have an error please upload it over to pastebin.com and send it there as well.

**Closed by kangarko** 2020-02-09 09:07 UTC
